on: 
  push:
    branches:
    - main
      name: yeshua books deploy
      jobs:
        web-deploy:
          name: Deploy
            runs-on: ubuntu-latest
            steps:
            - name: Get latest code
              uses: actions/checkout@v2
              with:
                server: ftp.yeshuabooks.com.ng
                username: ${{secrets.ftp_name}}
                password: ${{secrets.ftp_password}} 
